# Generated by Django 3.0.5 on 2020-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('D_O_B', models.DateField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(choices=[('FL', 'Florida'), ('CO', 'Colorado'), ('AZ', 'Arizona')], max_length=2)),
                ('zipcode', models.PositiveIntegerField()),
            ],
        ),
    ]
